name: distr-dev

services:
  postgres:
    image: 'postgres:17.5-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: distr
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
  mailpit:
    image: 'axllent/mailpit:v1.29.0'
    ports:
      - '1025:1025'
      - '8025:8025'
  minio:
    image: 'minio/minio:RELEASE.2025-02-28T09-55-16Z'
    entrypoint: sh
    command:
      - -c
      - mkdir -p /data/distr && minio server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - 'MINIO_ROOT_USER=distr'
      - 'MINIO_ROOT_PASSWORD=distr123'
    volumes:
      - minio:/data/

volumes:
  postgres:
  minio:
